version: "3"

networks:
  app-challenge:
    driver: bridge

services:
  academy-auth:
    container_name: academy-auth-service
    restart: always
    build: ./academy-auth
    ports:
      - "3001:3001"
    volumes:
      - .:/academy-auth/usr/src/app
      - "/academy-auth/usr/src/app/node_modules"
    networks:
      - app-challenge
    environment:
      MYSQL_DATABASE_HOST: database
      MYSQL_DATABASE: academy
      MYSQL_DATABASE_PORT: 3306
      MYSQL_PASSWORD: academypasword
      MYSQL_USER: academy_root
    depends_on:
      - database

  academy-back:
    container_name: academy-back
    restart: always
    build: ./academy-back
    ports:
      - "3002:3002"
    volumes:
      - .:/academy-back/usr/src/app
      - "/academy-back/usr/src/app/node_modules"
    networks:
      - app-challenge
    environment:
      MYSQL_DATABASE_HOST: database
      MYSQL_DATABASE: academy
      MYSQL_DATABASE_PORT: 3306
      MYSQL_PASSWORD: academypasword
      MYSQL_USER: academy_root
    depends_on:
      - database

  academy-front:
    container_name: academy-front
    restart: always
    build: ./academy-front
    ports:
      - "3000:3000"
    volumes:
      - .:/academy-front/usr/src/app
      - "/academy-front/usr/src/app/node_modules"
    networks:
      - app-challenge
    environment:
      DATABASE_HOST: database
    depends_on:
      - database

  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: academy
      MYSQL_USER: academy_root
      MYSQL_PASSWORD: "academypasword"
    networks:
      - app-challenge
